// Code generated by protoc-gen-go.
// source: logitem.proto
// DO NOT EDIT!

/*
Package logfarm_proto is a generated protocol buffer package.

It is generated from these files:
	logitem.proto

It has these top-level messages:
	LogItem
*/
package logfarm_proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LogItem struct {
	CreateTime string   `protobuf:"bytes,1,opt,name=create_time,json=createTime" json:"create_time,omitempty"`
	Filename   string   `protobuf:"bytes,2,opt,name=filename" json:"filename,omitempty"`
	Values     []string `protobuf:"bytes,3,rep,name=values" json:"values,omitempty"`
	Separator  string   `protobuf:"bytes,4,opt,name=separator" json:"separator,omitempty"`
}

func (m *LogItem) Reset()                    { *m = LogItem{} }
func (m *LogItem) String() string            { return proto.CompactTextString(m) }
func (*LogItem) ProtoMessage()               {}
func (*LogItem) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *LogItem) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

func (m *LogItem) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *LogItem) GetValues() []string {
	if m != nil {
		return m.Values
	}
	return nil
}

func (m *LogItem) GetSeparator() string {
	if m != nil {
		return m.Separator
	}
	return ""
}

func init() {
	proto.RegisterType((*LogItem)(nil), "logfarm.proto.LogItem")
}

func init() { proto.RegisterFile("logitem.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 147 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0xc9, 0x4f, 0xcf,
	0x2c, 0x49, 0xcd, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x02, 0x71, 0xd3, 0x12, 0x8b, 0xa0,
	0x5c, 0xa5, 0x1a, 0x2e, 0x76, 0x9f, 0xfc, 0x74, 0xcf, 0x92, 0xd4, 0x5c, 0x21, 0x79, 0x2e, 0xee,
	0xe4, 0xa2, 0xd4, 0xc4, 0x92, 0xd4, 0xf8, 0x92, 0xcc, 0xdc, 0x54, 0x09, 0x46, 0x05, 0x46, 0x0d,
	0xce, 0x20, 0x2e, 0x88, 0x50, 0x48, 0x66, 0x6e, 0xaa, 0x90, 0x14, 0x17, 0x47, 0x5a, 0x66, 0x4e,
	0x6a, 0x5e, 0x62, 0x6e, 0xaa, 0x04, 0x13, 0x58, 0x16, 0xce, 0x17, 0x12, 0xe3, 0x62, 0x2b, 0x4b,
	0xcc, 0x29, 0x4d, 0x2d, 0x96, 0x60, 0x56, 0x60, 0xd6, 0xe0, 0x0c, 0x82, 0xf2, 0x84, 0x64, 0xb8,
	0x38, 0x8b, 0x53, 0x0b, 0x12, 0x8b, 0x12, 0x4b, 0xf2, 0x8b, 0x24, 0x58, 0xc0, 0x9a, 0x10, 0x02,
	0x49, 0x6c, 0x60, 0x47, 0x18, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x5f, 0x11, 0x96, 0xf2, 0xa4,
	0x00, 0x00, 0x00,
}
